config/routes.rb
Rails.application.routes.draw do

  scope module: :core do
    resources :contractors
    resources :warehouses
    resources :products do
      resources :product_unit_of_measures
    end
    resources :unit_of_measures
    resources :services
    resources :resources
    resources :money
    resources :currency_rates
  end

  scope module: :purchases do
    resources :purchases
  end

  devise_for :users

  resources :users do
    member do
      get :edit_password
      put :update_password
    end
  end

  get 'company', to: 'core/company#show'
  get 'company/edit', to: 'core/company#edit'
  put 'company', to: 'core/company#update', as: 'company_update'

  get 'settings', to: 'settings#show'
  put 'settings', to: 'settings#update'

  root 'pages#index'
  get 'bali', to: 'pages#bali'

  resources :wizard
end

app/models/core.rb
module Core
  def self.table_name_prefix
    'core_'
  end
end

app/models/core/company.rb
class Core::Company < ActiveRecord::Base
  self.primary_key = :inn, :kpp
  validates :name, :full_name, :inn, :kpp, :currency, presence: true
  validates :inn, numericality: {greater_than: 0}
  validates :inn, length: { is: 10 }
  validates :kpp, numericality: {greater_than: 0}
  validates :kpp, length: { is: 9 }
  belongs_to :currency, foreign_key: "currency_code", class_name: "Core::Currency"
end

app/models/core/contractor.rb
class Core::Contractor < ActiveRecord::Base
  validates :name, presence: true
  has_many :purchases, class_name: "Purchases::Purchase"
end

app/models/core/currency.rb
class Core::Currency < ActiveRecord::Base
  self.primary_key = :code
  validates :name, :code, presence: true
  has_many :money, foreign_key: "currency_code"
  has_many :currency_rates, dependent: :destroy, foreign_key: "currency_code", class_name: "Core::CurrencyRate"
  has_many :companies, foreign_key: "currency_code", class_name: "Core::Company"
end

app/models/core/currency_rate.rb
class Core::CurrencyRate < ActiveRecord::Base
  validates :day, :currency, :rate, presence: true
  validates :rate, numericality: {greater_than: 0}
  validates :currency, uniqueness: { scope: :day, message: "One currency rate per day" }
  belongs_to :currency, foreign_key: "currency_code", class_name: "Core::Currency"
end

app/models/core/generators/generator.rb
module Core::Generators::Generator
  def on(active_record)
  	raise NotImplementedError
  end

  def next
  	raise NotImplementedError
  end
end

app/models/core/generators/simple_generator.rb
class Core::Generators::SimpleGenerator 
  include Core::Generators::Generator

  @active_record
  def on(active_record)
  	@active_record = active_record
  end

  def next
  	next_number = 1
    document = @active_record.last
    if document
      next_number = document.number.to_i + 1      
    end

    return next_number
  end
end

app/models/core/modules_settings.rb
class Core::ModulesSettings < Settingslogic
  source "#{Rails.root}/config/modules_settings.yml"
  namespace Rails.env
end

app/models/core/money.rb
class Core::Money < ActiveRecord::Base
  validates :currency, :amount, presence: true
  validates :amount, numericality: {greater_than: 0}
  belongs_to :currency, foreign_key: "currency_code", class_name: "Core::Currency"
end

app/models/core/product.rb
class Core::Product < ActiveRecord::Base
  validates :name, :article, presence: true
  has_many :product_unit_of_measures, dependent: :destroy, class_name: "Core::ProductUnitOfMeasure"
  has_many :unit_of_measures, through: :product_unit_of_measures, class_name: "Core::UnitOfMeasure"
end

app/models/core/product_unit_of_measure.rb
class Core::ProductUnitOfMeasure < ActiveRecord::Base
  validates :product, :unit_of_measure, :quantity, presence: true
  validates :unit_of_measure_id, :uniqueness => { :scope => :product_id,
    :message => I18n.t(:once_per_product) }
  validates :quantity, numericality: {greater_than: 0}
  belongs_to :product, class_name: "Core::Product"
  belongs_to :unit_of_measure, class_name: "Core::UnitOfMeasure"
end

app/models/core/purchases_settings.rb
class Core::PurchasesSettings < Settingslogic
  source "#{Rails.root}/config/purchases.yml"
  namespace Rails.env
end

app/models/core/resource.rb
class Core::Resource < ActiveRecord::Base
  validates :name, presence: true
end

app/models/core/service.rb
class Core::Service < ActiveRecord::Base
  validates :name, presence: true
end

app/models/core/unit_of_measure.rb
class Core::UnitOfMeasure < ActiveRecord::Base
  validates :name, presence: true
  validates :name, :uniqueness => { :case_sensitive => false }
  has_many :product_unit_of_measure, dependent: :destroy, class_name: "Core::productUnitOfMeasure"
  has_many :products, through: :product_unit_of_measures, class_name: "Core::Product"
end

app/models/core/warehouse.rb
class Core::Warehouse < ActiveRecord::Base
  validates :name, presence: true
  has_many :purchases, class_name: "Purchases::Purchase"
end

app/controllers/core/company_controller.rb
class Core::CompanyController < ApplicationController
  load_and_authorize_resource
  before_action :set_company, only: [:show, :edit, :update]

  # GET /company
  def show
  end

  # GET /company/edit
  def edit
    @company = Core::Company.first
    @currencies = Core::Currency.all
  end

  # POST /company
  def update
    @currencies = Core::Currency.all
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_path, notice: t(:company_updated) }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Core::Company.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:core_company).permit(:name, :full_name, :inn, :kpp, :currency_code)
    end
end

app/controllers/core/contractors_controller.rb
class Core::ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]

  # GET /core/contractors
  # GET /core/contractors.json
  def index
    @search = Core::Contractor.search(params[:q])
    @contractors = @search.result.page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @contractors }
    end
  end

  # GET /core/contractors/1
  # GET /core/contractors/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @contractor }
    end
  end

  # GET /core/contractors/new
  def new
    @contractor = Core::Contractor.new
  end

  # GET /core/contractors/1/edit
  def edit
  end

  # POST /core/contractors
  # POST /core/contractors.json
  def create
    @contractor = Core::Contractor.new(contractor_params)

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to contractors_path, notice: t(:contractor_created) }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /core/contractors/1
  # PATCH/PUT /core/contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to contractors_path, notice: t(:contractor_updated) }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /core/contractors/1
  # DELETE /core/contractors/1.json
  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_path, notice: t(:contractor_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Core::Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params.require(:core_contractor).permit(:name)
    end
end

app/controllers/core/currency_rates_controller.rb
class Core::CurrencyRatesController < ApplicationController
  before_action :set_variables, except: :destroy
  before_action :set_currency_rate, only: [:show, :edit, :update, :destroy]

  # GET /currency_rates
  # GET /currency_rates.json
  def index
    @search = Core::CurrencyRate.search(params[:q])
    @currency_rates = @search.result.page(params[:page])
  end

  # GET /currency_rates/1
  # GET /currency_rates/1.json
  def show
  end

  # GET /currency_rates/new
  def new
    @currency_rate = Core::CurrencyRate.new
  end

  # GET /currency_rates/1/edit
  def edit
  end

  # POST /currency_rates
  # POST /currency_rates.json
  def create
    @currency_rate = Core::CurrencyRate.new(currency_rate_params)

    respond_to do |format|
      if @currency_rate.save
        format.html { redirect_to currency_rates_path, notice: t(:currency_rate_created) }
        format.json { render :show, status: :created, location: @currency_rate }
      else
        format.html { render :new }
        format.json { render json: @currency_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currency_rates/1
  # PATCH/PUT /currency_rates/1.json
  def update
    respond_to do |format|
      if @currency_rate.update(currency_rate_params)
        format.html { redirect_to currency_rates_path, notice: t(:currency_rate_updated) }
        format.json { render :show, status: :ok, location: @currency_rate }
      else
        format.html { render :edit }
        format.json { render json: @currency_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currency_rates/1
  # DELETE /currency_rates/1.json
  def destroy
    @currency_rate.destroy
    respond_to do |format|
      format.html { redirect_to currency_rates_path, notice: t(:currency_rate_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency_rate
      @currency_rate = Core::CurrencyRate.find(params[:id])
    end

    def set_variables
      @currencies = Core::Currency.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_rate_params
      params.require(:core_currency_rate).permit(:currency_code, :day, :rate)
    end
end

app/controllers/core/money_controller.rb
class Core::MoneyController < ApplicationController
  before_action :set_money, only: [:show, :edit, :update, :destroy]
  before_action :set_veriables, except: :destroy

  # GET /money
  # GET /money.json
  def index
    @search = Core::Money.search(params[:q])
    @money = @search.result.page(params[:page])
  end

  # GET /money/1
  # GET /money/1.json
  def show
  end

  # GET /money/new
  def new
    @money = Core::Money.new
  end

  # GET /money/1/edit
  def edit
  end

  # POST /money
  # POST /money.json
  def create
    @money = Core::Money.new(money_params)

    respond_to do |format|
      if @money.save
        format.html { redirect_to money_index_path, notice: t(:money_created) }
        format.json { render :show, status: :created, location: @money }
      else
        format.html { render :new }
        format.json { render json: @money.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money/1
  # PATCH/PUT /money/1.json
  def update
    respond_to do |format|
      if @money.update(money_params)
        format.html { redirect_to money_index_path, notice: t(:money_updated) }
        format.json { render :show, status: :ok, location: @money }
      else
        format.html { render :edit }
        format.json { render json: @money.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money/1
  # DELETE /money/1.json
  def destroy
    @money.destroy
    respond_to do |format|
      format.html { redirect_to money_index_path, notice: t(:money_destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money
      @money = Core::Money.find(params[:id])
    end

    def set_veriables
      @currencies = Core::Currency.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def money_params
      params.require(:core_money).permit(:currency_code, :amount)
    end
end

app/views/core/resources/_form.html.slim
-if @resource.errors.any?
  .alert.alert-danger
    button type="button" class="close" data-dismiss="alert"
      | &times;
    h4=t('errors.title')
    ul
    - @resource.errors.full_messages.each do |msg|
      li= msg
= form_for @resource, url: (@resource.persisted? ? resource_path(@resource) : resources_path), :html => { :class => "form-horizontal" } do |f|
  .form-group
    = f.label t(:name), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_field :name, :class => 'text_field form-control'
  .form-group
    = f.label t(:desc), :class => 'control-label col-md-2'
    .col-sm-3
      = f.text_area :desc, :class => 'text_field form-control', rows: 6
  .form-group
    .col-md-offset-2.col-sm-3
      =' f.button t(:save), :class =>'btn btn-primary', :disable_with => t(:please_wait)
      = link_to t(:cancel), resources_path, :class => 'btn btn-default'

app/views/core/resources/edit.html.slim
div class="page-header"
  h1=t(:edit_resource)
= render :partial => "form"

app/views/core/resources/index.html.slim
.page-header
  h1=t(:resources)
p
  button.btn.btn-primary type="button" class="" data-toggle="collapse" data-target="#filter"
    = fa_icon "search", text: t(:filter)
#filter.collapse
  .well.well-small
    = search_form_for @search, url: resources_path, class: "form-horizontal" do |f|
      .form-group
        = f.label :name_cont, t(:name)+':', class: "col-sm-2 control-label"
        .col-sm-3
          = f.text_field :name_cont, class: 'search-field form-control'
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button t(:search), class: 'btn btn-info btn-search'
          '
          button.btn.btn-info type="button" id="q_reset"
            =t(:reset)
table.table.table-striped
  thead
    tr
      th= sort_link @search, :name, t(:name)
      th= t(:actions)
  tbody
    - @resources.each do |resource|
      tr
        td= resource.name
        td
          = link_to resource_path(resource), class: "btn btn-xs"
            = fa_icon "info-circle lg", title: t(:show)

          = link_to edit_resource_path(resource), class: "btn btn-xs"
            = fa_icon "edit lg", title: t(:edit)

          = link_to resource_path(resource), class: "btn btn-xs", :method => :delete, :data => { :confirm => t(:are_you_sure)}
            = fa_icon "remove", title: t(:remove)
= paginate @resources
p
  .page_entries_info
    = page_entries_info @resources
= link_to t(:new_resource), new_resource_path, :class => 'btn btn-default btn-new'

app/views/core/resources/new.html.slim
.page-header
  h1=t(:new_resource)
= render :partial => "form"

app/views/core/resources/show.html.slim
.page-header
  h1=t(:resource)

.fieldset
  dl
    dt.label.label-default= t(:name)
    dd
      pre.prettyprint= @resource.name
    dt.label.label-default= t(:desc)
    dd
      pre.prettyprint= @resource.desc

.form-group
  = link_to t(:back), resources_path, :class => 'btn btn-default btn-back'
  '
  = link_to t(:edit), edit_resource_path(@resource), :class => 'btn btn-default btn-edit'
  '
  = link_to t(:remove), resource_path(@resource), :method => "delete", :data => { :confirm => t(:are_you_sure) }, :class => 'btn btn-danger btn-remove'